In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('seasonal_disparities_20th_century.csv')

In [3]:
df.head()

,FIPSCode,YEAR,Season,TEMPERATURE_MA,TEMPERATURE_DEVIATION_STDDEV,TEMPERATURE_INDEX,PRECIPITATION_MA,PRECIPITATION_DEVIATION_STDDEV,PRECIPITATION_INDEX
0,6001,2021,Summer,68.7,1.847292,Normal,0.00,-0.686548,Normal
1,6005,2021,Winter,42.6,-0.506057,Normal,12.34,1.702105,Normal
2,6009,2021,Winter,42.6,-0.542606,Normal,10.80,1.422228,Normal
3,6019,2021,Winter,41.0,0.454152,Normal,6.96,1.639776,Normal
4,6029,2021,Summer,79.3,2.528477,Hotter,0.05,-0.067581,Normal

In [39]:
np.sqrt((1.847292 ** 2) * 5) - 68.7

-64.56932951370847

In [50]:
-(np.sqrt((1.847292 ** 2) * 5/6) - 68.7)

67.01366083550195

In [60]:
#reverse std
avg_20_precip = []
avg_20_temp = []
for val in df.iterrows():

    #print(val[1][4])
    temp_std = val[1][4]
    temp_ma = val[1][3]

    precip_std = val[1][7]
    precip_ma = val[1][6]

    avg_20_temp.append(-(np.sqrt((temp_std ** 2 ) * 5) - temp_ma))
    avg_20_precip.append(-(np.sqrt((precip_std ** 2 ) * 5) - precip_ma))

In [61]:
df['temp_avg_20'] = avg_20_temp
df['precip_avg_20'] = avg_20_precip

In [46]:
df.head()

,FIPSCode,YEAR,Season,TEMPERATURE_MA,TEMPERATURE_DEVIATION_STDDEV,TEMPERATURE_INDEX,PRECIPITATION_MA,PRECIPITATION_DEVIATION_STDDEV,PRECIPITATION_INDEX,temp_avg_20,precip_avg_20
0,6001,2021,Summer,68.7,1.847292,Normal,0.00,-0.686548,Normal,64.569330,-1.535168
1,6005,2021,Winter,42.6,-0.506057,Normal,12.34,1.702105,Normal,41.468421,8.533979
2,6009,2021,Winter,42.6,-0.542606,Normal,10.80,1.422228,Normal,41.386695,7.619801
3,6019,2021,Winter,41.0,0.454152,Normal,6.96,1.639776,Normal,39.984486,3.293348
4,6029,2021,Summer,79.3,2.528477,Hotter,0.05,-0.067581,Normal,73.646155,-0.101115

In [62]:
df2 = df[['FIPSCode','YEAR', 'Season', 'TEMPERATURE_MA', 'PRECIPITATION_MA', 'temp_avg_20', 'precip_avg_20']]
df2.head()

,FIPSCode,YEAR,Season,TEMPERATURE_MA,PRECIPITATION_MA,temp_avg_20,precip_avg_20
0,6001,2021,Summer,68.7,0.00,64.569330,-1.535168
1,6005,2021,Winter,42.6,12.34,41.468421,8.533979
2,6009,2021,Winter,42.6,10.80,41.386695,7.619801
3,6019,2021,Winter,41.0,6.96,39.984486,3.293348
4,6029,2021,Summer,79.3,0.05,73.646155,-0.101115

In [55]:
fips = df2.groupby(df2.FIPSCode)

In [258]:
precip_change_w = {}
precip_change_s = {}

for dfs in fips:
    #print(dfs)
    fip = dfs[0]
    df = dfs[1] #get the df
    
    #print(df)
    #print(fip)
    winter_p = df[df.Season == 'Winter']
    summer_p = df[df.Season == 'Summer']

    #sort by year
    precip_w  = winter_p.sort_values(by='YEAR', ascending=False).PRECIPITATION_MA.pct_change()
    precip_s = summer_p.sort_values(by='YEAR', ascending=False).PRECIPITATION_MA.pct_change()

    #Percentage change between the current and a prior element.
    #precip_change_w[fip] = precip_w.tolist()

    #precip_change_s[fip] = precip_s.tolist()
    
    #temp = df.TEMPERATURE_MA.pct_change()
    #temp_change[fip] = temp.tolist()

In [259]:
## temp / precip dict {'fips': percent change yoy}
len(temp_change_s[1001])

22

In [131]:
fips_df = pd.read_excel('County-Type-Share.xlsx', sheet_name='Sheet1')

/Users/ally/anaconda3/lib/python3.7/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [312]:
fips_df.County.unique().shape

(3143,)

In [307]:
fips_names = pd.read_excel('County-Type-Share.xlsx', sheet_name='Sheet2')
fips_names.columns = ['key', 'names']
fips_dict = {}
for row in fips_names.iterrows() :
    key = row[0]+1
    name = row[1]
    fips_dict[key] = name.names

In [308]:
fips_dict

{1: 'Exurbs',
 2: 'Graying America',
 3: 'African American South',
 4: 'Evangelical Hubs',
 5: 'Working Class Country',
 6: 'Military Posts',
 7: 'Urban Suburbs',
 8: 'Hispanic Centers',
 9: 'Native American Lands',
 10: 'Rural Middle America',
 11: 'College Towns',
 12: 'LDS Enclaves',
 13: 'Aging Farmlands',
 14: 'Big Cities',
 15: 'Middle Suburbs'}

In [133]:
fips_code = fips_df[['Type Number', 'FIPS']]
fips_code.columns = ['Type', 'FIPSCode']

In [134]:
df2[df2.FIPSCode == 11001]

       FIPSCode  YEAR  Season  TEMPERATURE_MA  PRECIPITATION_MA
62212     11001  2021  Summer            74.8              3.35
62213     11001  2021  Summer            74.8              4.41
62247     11001  2021  Winter            45.8              1.41
62248     11001  2021  Winter            45.8              0.68
63089     11001  2020  Summer            74.5              3.94
...         ...   ...     ...             ...               ...
80819     11001  2007  Summer            74.4              2.31
81797     11001  2006  Winter            43.5              2.07
81798     11001  2006  Winter            43.5              1.72
81984     11001  2006  Summer            73.2              5.20
81985     11001  2006  Summer            73.2             11.83

[88 rows x 5 columns]

In [262]:
for val in precip_change_s:
    arr = precip_change_s[val]
    
    if len(arr) != 22:
        print(val)
        print(arr)

11001
[nan, 0.31641791044776113, -0.10657596371882094, 0.055837563451776706, 0.05048076923076916, -0.1235697940503433, 1.3446475195822454, -0.35523385300668153, -0.30224525043177897, -0.7029702970297029, 2.966666666666667, -0.2373949579831932, 1.2534435261707988, 0.3374083129584351, -0.6755027422303473, 0.46197183098591577, -0.18689788053949918, 0.924170616113744, -0.6650246305418719, 0.011029411764705843, -0.043636363636363695, -0.34980988593155893, 0.14035087719298245, 0.2512820512820513, 1.5737704918032787, -0.15923566878980888, 0.05681818181818188, -0.14874551971326166, -0.5136842105263157, 0.8095238095238093, 0.2440191387559809, 1.275, -0.7650042265426881, -0.046762589928057485, 0.7396226415094342, -0.18655097613882865, 1.12, -0.16855345911949682, -0.5869894099848714, 0.08058608058608074, 0.7084745762711864, 0.029761904761904878, -0.1695568400770714, 0.10208816705336443]
15003
[nan, 0.6666666666666667, 55.8, -0.9735915492957746, 2.5333333333333337, -0.6415094339622642, 0.21052631578947367, 1.5217391304347823, -0.7068965517241379, -0.6470588235294118, 21.666666666666668, -0.8382352941176471, 1.5, -0.7090909090909091, -0.4375, 2.1111111111111116, 0.10714285714285698, -0.35483870967741926, -0.6499999999999999, 15.57142857142857, -0.9741379310344828]
24001
[nan, 0.31641791044776113, -0.10657596371882094, 0.055837563451776706, 0.05048076923076916, -0.1235697940503433, 1.3446475195822454, -0.35523385300668153, -0.30224525043177897, -0.7029702970297029, 2.966666666666667, -0.2373949579831932, 1.2534435261707988, 0.3374083129584351, -0.6755027422303473, 0.46197183098591577, -0.18689788053949918, 0.924170616113744, -0.6650246305418719, 0.011029411764705843, -0.043636363636363695, -0.34980988593155893, 0.14035087719298245, 0.2512820512820513, 1.5737704918032787, -0.15923566878980888, 0.05681818181818188, -0.14874551971326166, -0.5136842105263157, 0.8095238095238093, 0.2440191387559809, 1.275, -0.7650042265426881, -0.046762589928057485, 0.7396226415094342, -0.18655097613882865, 1.12, -0.16855345911949682, -0.5869894099848714, 0.08058608058608074, 0.7084745762711864, 0.029761904761904878, -0.1695568400770714, 0.10208816705336443]

In [263]:
f11001 = precip_change_s.pop(11001)
f15003 = precip_change_s.pop(15003)
f24001 = precip_change_s.pop(24001)

In [245]:
winter = []
summer = []
years = df.YEAR.unique()
years_sorted = np.sort(years)
years_sorted = years_sorted[::-1]
for year in years_sorted:
    winter.append('W_' + str(year))
    summer.append('S_' + str(year))

In [282]:
precip_df = pd.DataFrame.from_dict(precip_change_w)
summ = pd.DataFrame.from_dict(precip_change_s)

#precip_df.columns = winter
#summ.columns = summer

In [265]:
precip_df = precip_df.T
precip_df.columns = winter
summ = summ.T
summ.columns = summer

In [266]:
precip_df = precip_df.join(summ)

In [267]:
type_col = []
for i, row in precip_df.iterrows():
    fips = i
    
    #print(fips)
    try:
        type_ = fips_code.loc[fips_code.FIPSCode == fips].iloc[0].Type
        type_col.append(type_)
    except:
        type_col.append(fips)

In [268]:
precip_df['type'] = type_col

In [269]:
import numpy as np
no_inf = precip_df.replace([np.inf, -np.inf], np.nan)

In [270]:
no_inf[no_inf.type == 6]['W_2018'].mean()

0.8719218027873307

In [283]:
df_agg = no_inf.drop(columns=['W_2021', 'S_2021'])
type_date_avg = df_agg.groupby(df_agg.type).mean()
#type_date_max = df_agg.groupby(df_agg.type).max()
#type_date_min = df_agg.groupby(df_agg.type).min()

In [285]:
type_date_avg

,W_2020,W_2019,W_2018,W_2017,W_2016,W_2015,W_2014,W_2013,W_2012,W_2011,...,S_2009,S_2008,S_2007,S_2006,S_2005,S_2004,S_2003,S_2002,S_2001,S_2000
type,,,,,,,,,,,,,,,,,,,,,
1,1.474968,0.300806,0.863944,-0.523364,1.587918,1.402313,-0.339247,0.278922,0.545032,0.437464,...,1.626970,0.110135,1.047549,0.399262,0.675506,1.636929,0.200235,-0.188902,0.740361,0.894544
2,3.023389,0.902043,0.446365,-0.252122,5.195498,0.637174,-0.114734,0.199790,1.476697,2.082095,...,1.279161,0.055319,0.817933,0.246108,1.247722,0.673898,0.076509,0.824148,0.719097,2.110267
3,0.739852,0.407769,1.071254,-0.514531,0.471696,0.641182,-0.239532,0.271090,0.027913,-0.127812,...,0.002143,0.491499,1.029686,0.073295,0.676069,2.014899,-0.043799,-0.506307,1.386177,-0.203404
4,2.924439,0.259033,1.307777,-0.563294,1.120643,2.348029,-0.484904,0.521272,-0.063845,0.719146,...,0.104199,0.413669,0.601181,-0.109631,0.511695,1.368918,0.090248,-0.410269,0.613424,0.900796
5,0.721794,0.508155,0.930555,-0.522586,1.059001,1.670903,-0.497370,0.635818,-0.051043,0.700764,...,0.093475,0.379814,0.437892,0.200387,0.010815,1.560812,0.246689,-0.187371,0.321953,0.637919
6,2.616528,0.754281,0.871922,-0.427334,1.112454,0.649167,-0.053039,0.470665,0.171674,0.536423,...,0.230237,0.323228,0.686183,0.299463,0.533019,0.864193,0.242550,-0.209600,1.274142,0.920337
7,1.600783,0.877460,0.253118,-0.397607,13.448259,0.564040,0.346391,0.050276,1.937866,0.911887,...,1.380283,-0.149963,0.108099,1.142454,4.687568,0.485486,0.808169,-0.139746,0.927051,0.054118
8,5.156193,1.943674,1.437093,-0.444914,9.436861,0.651762,0.480126,0.059557,2.914022,7.636011,...,1.715256,0.106800,3.777244,-0.116628,0.253562,4.724602,-0.140344,0.317625,0.137883,5.099723
9,-0.460111,1.474501,0.364220,-0.161373,10.810190,0.141490,0.278007,1.480103,0.459430,0.146630,...,0.567234,0.336252,-0.047598,-0.006870,1.216870,-0.157235,0.094475,-0.095742,1.130283,0.478172
10,1.880362,0.903405,0.339519,-0.568187,2.456129,1.577252,-0.392274,0.212430,0.940751,0.666635,...,-0.187324,0.312202,-0.283958,0.248561,0.532556,0.263976,0.234920,0.106196,0.313325,0.513658
11,3.230333,0.580343,0.678735,-0.503007,3.597448,1.536255,-0.382370,0.244484,1.125906,0.334744,...,0.225529,0.253623,0.253983,0.473004,0.592963,0.621922,0.217365,0.625735,0.773138,0.618414
12,-0.634994,1.038665,-0.328277,-0.324776,5.594430,-0.281127,-0.043900,-0.218898,0.978274,-0.715850,...,1.228799,-0.661417,-0.018491,0.581041,3.794252,-0.389508,-0.356038,-0.109006,2.777499,0.302444
13,4.347747,1.959210,0.761608,-0.489424,3.730875,0.637131,-0.088024,2.369379,2.884172,1.616819,...,-0.025200,0.207498,0.027213,-0.169763,1.765146,-0.249225,0.476028,-0.202062,0.591922,0.798839
14,1.573440,1.108606,0.633630,-0.459476,19.419590,1.640168,0.162845,-0.040822,1.905250,0.820204,...,0.987492,0.069655,1.847952,0.340364,0.194926,1.583004,0.399974,-0.041884,0.544034,0.701333
15,0.538015,0.368590,0.116522,-0.544847,1.198286,0.884704,-0.417463,0.403546,0.286282,-0.030553,...,0.046642,0.231695,-0.283189,0.567239,-0.339412,0.880747,0.196985,0.005525,0.126669,0.486378
2158,-0.802935,-0.329787,-0.015873,0.854839,-0.626087,0.651163,0.985915,0.567376,-0.502262,0.581818,...,0.099338,0.421687,-0.241525,-0.033520,0.063584,0.086957,0.025000,-0.395122,-0.120968,-0.027523
46102,-0.621622,1.428571,0.132353,-0.311688,1.037736,-0.037037,-0.432692,-0.084746,-0.425926,-0.064516,...,-0.117500,-0.031161,-0.672515,0.732143,1.041237,-0.636364,1.020833,-0.738832,3.802632,-0.569863

In [277]:
type_date_avg.to_csv('type_avg_precip.csv')

In [286]:
for col in type_date_avg.columns:
    print(col + ': row.'+ col + ',')

W_2020: row.W_2020,
W_2019: row.W_2019,
W_2018: row.W_2018,
W_2017: row.W_2017,
W_2016: row.W_2016,
W_2015: row.W_2015,
W_2014: row.W_2014,
W_2013: row.W_2013,
W_2012: row.W_2012,
W_2011: row.W_2011,
W_2010: row.W_2010,
W_2009: row.W_2009,
W_2008: row.W_2008,
W_2007: row.W_2007,
W_2006: row.W_2006,
W_2005: row.W_2005,
W_2004: row.W_2004,
W_2003: row.W_2003,
W_2002: row.W_2002,
W_2001: row.W_2001,
W_2000: row.W_2000,
S_2020: row.S_2020,
S_2019: row.S_2019,
S_2018: row.S_2018,
S_2017: row.S_2017,
S_2016: row.S_2016,
S_2015: row.S_2015,
S_2014: row.S_2014,
S_2013: row.S_2013,
S_2012: row.S_2012,
S_2011: row.S_2011,
S_2010: row.S_2010,
S_2009: row.S_2009,
S_2008: row.S_2008,
S_2007: row.S_2007,
S_2006: row.S_2006,
S_2005: row.S_2005,
S_2004: row.S_2004,
S_2003: row.S_2003,
S_2002: row.S_2002,
S_2001: row.S_2001,
S_2000: row.S_2000,

In [60]:
no_inf.type.unique()

array([    1,     2,     3,     4,     5,     6,     7,     9,  2158,
          10,    11,    14,     8,    15,    12,    13, 46102])

In [32]:
type_date_max.to_csv('type_max.csv')

In [58]:
type_avg_T.to_csv('type_avg_T.csv')

In [46]:
col = []
for i in range(1, 18) :
    col.append('T' + str(i))

NameError: name 'type_date_avg' is not defined

In [57]:
type_avg_T = type_date_avg.T
type_avg_T.columns = col

type_avg_T = type_avg_T.drop(columns=['T16', 'T17'], axis=0)
type_avg_T.head()

,T1,T2,T3,T4,T5,T6,T7,T8,T9,T10,T11,T12,T13,T14,T15
S_2021,0.086548,0.300954,0.024100,0.018575,0.086234,0.148305,0.064325,0.037886,0.329241,0.287356,0.331373,-0.048203,0.636836,0.207152,0.100005
W_2020,0.077116,0.164006,0.001327,0.049570,0.115832,0.246275,0.071290,0.093993,-2.991993,0.198599,0.174365,0.393828,0.544063,0.040877,0.177160
S_2020,0.196341,0.160707,0.043701,0.091064,0.155237,0.275555,0.133861,0.130406,0.553499,0.321650,0.100920,0.209287,0.327870,0.122203,0.105706
W_2019,0.132841,0.240047,0.188513,0.238903,0.248616,0.286328,0.112337,0.199881,0.812179,0.259358,0.300792,0.303500,0.225222,0.282382,0.288846
S_2019,0.240857,0.169215,0.047412,0.038834,0.134046,3.215899,0.165068,0.076691,-0.625200,0.288949,0.139862,0.414777,0.536177,-0.102867,0.189590

In [22]:
type_date_avg.columns

NameError: name 'type_date_avg' is not defined